import { Category, Question, QuestionDifficulty } from '../types';

type DifficultyBank = Record<QuestionDifficulty, Question[]>;

type QuestionTypeBank = {
  multipleChoice: DifficultyBank;
  openEnded: DifficultyBank;
};

type QuestionBank = {
  [key in Category]: QuestionTypeBank;
};

export const questionBank: QuestionBank = {
  [Category.Sport]: {
    multipleChoice: {
        easy: [
            { question: "Jak se nazývá zimní sport kombinující běh na lyžích a střelbu?", options: ["Biatlon", "Severská kombinace", "Skikros", "Curling"], correctAnswer: "Biatlon", difficulty: "easy" },
            { question: "Ve kterém městě se konaly letní olympijské hry v roce 2016?", options: ["Londýn", "Tokio", "Rio de Janeiro", "Peking"], correctAnswer: "Rio de Janeiro", difficulty: "easy" },
            { question: "Jak se jmenuje nejslavnější cyklistický závod na světě?", options: ["Giro d'Italia", "Vuelta a España", "Tour de France", "Paříž-Roubaix"], correctAnswer: "Tour de France", difficulty: "easy" },
            { question: "V jakém sportu proslul Michael Jordan?", options: ["Baseball", "Basketbal", "Americký fotbal", "Lední hokej"], correctAnswer: "Basketbal", difficulty: "easy" },
            { question: "Kolik kruhů je na olympijské vlajce?", options: ["Čtyři", "Pět", "Šest", "Sedm"], correctAnswer: "Pět", difficulty: "easy" },
            { question: "Jaká barva karty znamená vyloučení hráče ve fotbale?", options: ["Žlutá", "Zelená", "Modrá", "Červená"], correctAnswer: "Červená", difficulty: "easy" },
            { question: "Ve kterém sportu se používá 'puk'?", options: ["Pozemní hokej", "Florbal", "Lední hokej", "Curling"], correctAnswer: "Lední hokej", difficulty: "easy" },
            { question: "Který sport se hraje na Wimbledonu?", options: ["Golf", "Tenis", "Kroket", "Badminton"], correctAnswer: "Tenis", difficulty: "easy" },
            { question: "Jak se nazývá hod, kterým se v basketbalu získávají 3 body?", options: ["Smeč", "Trojka", "Dvojtakt", "Šestka"], correctAnswer: "Trojka", difficulty: "easy" },
            { question: "Který z těchto sportů se nehraje s míčem?", options: ["Volejbal", "Házená", "Badminton", "Rugby"], correctAnswer: "Badminton", difficulty: "easy" },
            { question: "Jak se nazývá vedoucí jezdec v celkovém pořadí Tour de France?", options: ["Král hor", "Sprinter", "Muž ve žlutém", "Kapitán"], correctAnswer: "Muž ve žlutém", difficulty: "easy" },
            { question: "Co znamená pojem 'home run' v baseballu?", options: ["Chyba nadhozu", "Dokonalý odpal", "Rychlý běh", "Výměna hráče"], correctAnswer: "Dokonalý odpal", difficulty: "easy" },
            { question: "Ve kterém sportu soutěží týmy o Stanley Cup?", options: ["Baseball", "Basketbal", "Americký fotbal", "Lední hokej"], correctAnswer: "Lední hokej", difficulty: "easy" },
            { question: "Kolik hráčů tvoří standardní volejbalový tým na hřišti?", options: ["5", "6", "7", "8"], correctAnswer: "6", difficulty: "easy" },
        ],
        medium: [
             { question: "Která země vyhrála první Mistrovství světa ve fotbale v roce 1930?", options: ["Brazílie", "Argentina", "Itálie", "Uruguay"], correctAnswer: "Uruguay", difficulty: "medium" },
             { question: "Kolik bodů má v šachu nejcennější figura, královna?", options: ["3", "5", "9", "Nekonečno"], correctAnswer: "9", difficulty: "medium" },
             { question: "Který atlet drží světový rekord v běhu na 100 metrů?", options: ["Tyson Gay", "Yohan Blake", "Justin Gatlin", "Usain Bolt"], correctAnswer: "Usain Bolt", difficulty: "medium" },
             { question: "Jak se jmenuje technika skoku do výšky, při které atlet přeskakuje laťku zády napřed?", options: ["Nůžky", "Straddle", "Fosbury Flop", "Western Roll"], correctAnswer: "Fosbury Flop", difficulty: "medium" },
             { question: "V jaké zemi vzniklo karate?", options: ["Japonsko", "Čína", "Korea", "Thajsko"], correctAnswer: "Japonsko", difficulty: "medium" },
             { question: "Který plavecký styl je považován za nejnáročnější?", options: ["Kraul", "Znak", "Prsa", "Motýlek"], correctAnswer: "Motýlek", difficulty: "medium" },
             { question: "Jak se nazývá aréna pro býčí zápasy?", options: ["Koloseum", "Hipodrom", "Plaza de Toros", "Velodrom"], correctAnswer: "Plaza de Toros", difficulty: "medium" },
             { question: "Který tým NBA má nejvíce titulů v historii?", options: ["Los Angeles Lakers", "Chicago Bulls", "Boston Celtics", "Golden State Warriors"], correctAnswer: "Boston Celtics", difficulty: "medium" },
             { question: "Co je to 'peloton' v cyklistice?", options: ["Vedoucí skupina", "Hlavní pole jezdců", "Únik", "Cílová rovinka"], correctAnswer: "Hlavní pole jezdců", difficulty: "medium" },
             { question: "V jakém sportu se udílí Zlatý míč?", options: ["Basketbal", "Fotbal", "Házená", "Rugby"], correctAnswer: "Fotbal", difficulty: "medium" },
             { question: "Která země je považována za kolébku golfu?", options: ["Anglie", "Irsko", "USA", "Skotsko"], correctAnswer: "Skotsko", difficulty: "medium" },
             { question: "Jak se nazývá nejstarší a nejprestižnější tenisový turnaj?", options: ["US Open", "French Open", "Australian Open", "Wimbledon"], correctAnswer: "Wimbledon", difficulty: "medium" },
        ],
        hard: [
             { question: "Který tenista drží rekord v počtu vyhraných grandslamových titulů v mužské dvouhře?", options: ["Roger Federer", "Rafael Nadal", "Novak Djokovič", "Pete Sampras"], correctAnswer: "Novak Djokovič", difficulty: "hard" },
             { question: "Který tým Formule 1 má nejvíce konstruktérských titulů?", options: ["McLaren", "Mercedes", "Ferrari", "Williams"], correctAnswer: "Ferrari", difficulty: "hard" },
             { question: "Kdo je jediným sportovcem v historii, který vyhrál zlatou medaili na letních i zimních olympijských hrách v různých sportech?", options: ["Shaun White", "Carl Lewis", "Eddie Eagan", "Usain Bolt"], correctAnswer: "Eddie Eagan", difficulty: "hard" },
             { question: "Jak se jmenuje cyklistický závod známý jako 'Peklo severu'?", options: ["Milán-San Remo", "Kolem Flander", "Liège-Bastogne-Liège", "Paříž-Roubaix"], correctAnswer: "Paříž-Roubaix", difficulty: "hard" },
             { question: "V jakém roce byl v boxu zaveden požadavek na nošení rukavic?", options: ["1867", "1892", "1905", "1921"], correctAnswer: "1867", difficulty: "hard" },
             { question: "Jak se nazývá nejdelší jamka v golfu?", options: ["Albatros", "Condor", "Par 6", "Eagle"], correctAnswer: "Par 6", difficulty: "hard" },
             { question: "Který boxer jako jediný v historii ukončil kariéru neporažen jako mistr světa v těžké váze?", options: ["Muhammad Ali", "Joe Louis", "Rocky Marciano", "Tyson Fury"], correctAnswer: "Rocky Marciano", difficulty: "hard" },
             { question: "Jak se jmenuje jediný kůň, který byl uveden do Síně slávy amerických sportů?", options: ["Seabiscuit", "War Admiral", "Man o' War", "Secretariat"], correctAnswer: "Secretariat", difficulty: "hard" },
             { question: "Kolik peříček má standardní badmintonový míček?", options: ["12", "14", "16", "18"], correctAnswer: "16", difficulty: "hard" },
             { question: "Která země hostila první Mistrovství světa v ragby v roce 1987?", options: ["Anglie", "Austrálie", "Nový Zéland", "Jižní Afrika"], correctAnswer: "Nový Zéland", difficulty: "hard" },
             { question: "V jakém sportu je cílem dosáhnout 'osmičky'?", options: ["Curling", "Veslování", "Šipky", "Lukostřelba"], correctAnswer: "Veslování", difficulty: "hard" },
             { question: "Jaký je název pro hod v kriketu, který se odrazí od země předtím, než dosáhne pálkaře?", options: ["Bouncer", "Yorker", "Googly", "Full toss"], correctAnswer: "Bouncer", difficulty: "hard" },
        ],
    },
    openEnded: {
        easy: [
            { question: "Kolik hráčů je na hřišti v jednom fotbalovém týmu?", correctAnswer: "11", difficulty: "easy" },
            { question: "Jak se v hokeji nazývá situace, kdy hráč vstřelí tři góly v jednom zápase?", correctAnswer: "Hattrick", difficulty: "easy" },
            { question: "Na jakém povrchu se hraje slavný tenisový turnaj Wimbledon?", correctAnswer: "Tráva", difficulty: "easy" },
            { question: "Z jaké země pochází fotbalista Lionel Messi?", correctAnswer: "Argentina", difficulty: "easy" },
            { question: "Jak se jmenuje sport, ve kterém se jezdí na koni a trefuje se do míčku dlouhou holí?", correctAnswer: "Pólo", difficulty: "easy" },
            { question: "Jak se nazývá aréna, kde se konají zápasy gladiátorů?", correctAnswer: "Koloseum", difficulty: "easy" },
            { question: "Jaké je hlavní město, které hostilo olympijské hry v roce 2008?", correctAnswer: "Peking", difficulty: "easy" },
            { question: "Jak se nazývá sportovní disciplína, která zahrnuje plavání, jízdu na kole a běh?", correctAnswer: "Triatlon", difficulty: "easy" },
            { question: "Jaká je barva míče v basketbalu?", correctAnswer: "Oranžová", difficulty: "easy" },
            { question: "Jak se nazývá úder v golfu, který pošle míček přímo do jamky na jeden pokus?", correctAnswer: "Hole-in-one", difficulty: "easy" },
            { question: "Kolik figur má každý hráč na začátku šachové partie?", correctAnswer: "16", difficulty: "easy" },
            { question: "Jak se nazývá japonský národní sport, kde zápasí těžcí zápasníci?", correctAnswer: "Sumo", difficulty: "easy" },
        ],
        medium: [
            { question: "Jak dlouhý je maratonský běh (v kilometrech, stačí celé číslo)?", correctAnswer: "42", difficulty: "medium" },
            { question: "Z jaké země pochází bojové umění judo?", correctAnswer: "Japonsko", difficulty: "medium" },
            { question: "Jak se jmenuje slavná sportovní hala v New Yorku, domov Knicks a Rangers?", correctAnswer: "Madison Square Garden", difficulty: "medium" },
            { question: "Jak se jmenuje poslední etapa v desetiboji?", correctAnswer: "Běh na 1500 metrů", difficulty: "medium" },
            { question: "Který fotbalový klub je známý pod přezdívkou 'Rudí ďáblové'?", correctAnswer: "Manchester United", difficulty: "medium" },
            { question: "Jak se nazývá hod v bowlingu, kterým se shodí všechny kuželky najednou?", correctAnswer: "Strike", difficulty: "medium" },
            { question: "Ve kterém roce se konaly první moderní olympijské hry?", correctAnswer: "1896", difficulty: "medium" },
            { question: "Jak se jmenuje slavná skokanská můstková soutěž konaná na přelomu roku v Německu a Rakousku?", correctAnswer: "Turné čtyř můstků", difficulty: "medium" },
            { question: "Jak se nazývá trofej pro vítěze Světového poháru v ragby?", correctAnswer: "Webb Ellis Cup", difficulty: "medium" },
            { question: "Jaký je název pro dva po sobě jdoucí striky v bowlingu?", correctAnswer: "Double", difficulty: "medium" },
            { question: "Z jaké země pochází Pelé?", correctAnswer: "Brazílie", difficulty: "medium" },
            { question: "Jak se nazývá nejvyšší možná kombinace v pokeru?", correctAnswer: "Royal Flush", difficulty: "medium" },
        ],
        hard: [
            { question: "Jaké je jméno nejvyšší hory světa, kterou se snaží zdolat horolezci?", correctAnswer: "Mount Everest", difficulty: "hard" },
            { question: "Jak se nazývá finálový zápas ligy amerického fotbalu (NFL)?", correctAnswer: "Super Bowl", difficulty: "hard" },
            { question: "Jak se jmenuje sport, který kombinuje prvky tenisu, badmintonu a stolního tenisu?", correctAnswer: "Pickleball", difficulty: "hard" },
            { question: "Jaké je celé jméno boxera Muhammada Aliho, které měl před konverzí k islámu?", correctAnswer: "Cassius Clay", difficulty: "hard" },
            { question: "Jak se nazývá tradiční skotský sport, kde se hází těžkou kládou?", correctAnswer: "Caber toss", difficulty: "hard" },
            { question: "Který stát USA je domovem proslulého závodu Indianapolis 500?", correctAnswer: "Indiana", difficulty: "hard" },
            { question: "Jak se jmenuje jediný tým, který dokončil celou sezónu NFL bez jediné porážky?", correctAnswer: "Miami Dolphins", difficulty: "hard" },
            { question: "Jaký je název pro situaci v kriketu, kdy pálkař skóruje 100 běhů v jedné směně?", correctAnswer: "Century", difficulty: "hard" },
            { question: "Jak se jmenuje cena pro nejužitečnějšího hráče finále NBA?", correctAnswer: "Bill Russell MVP Trophy", difficulty: "hard" },
            { question: "V jakém městě se nachází sídlo Mezinárodního olympijského výboru?", correctAnswer: "Lausanne", difficulty: "hard" },
            { question: "Jak se nazývá tradiční novozélandský válečný tanec, který předvádí rugbyový tým All Blacks?", correctAnswer: "Haka", difficulty: "hard" },
            { question: "Kdo je autorem moderního pětiboje?", correctAnswer: "Pierre de Coubertin", difficulty: "hard" },
        ],
    },
  },
  [Category.Esport]: {
    multipleChoice: {
        easy: [
            { question: "Která společnost vyvinula populární hru Fortnite?", options: ["Electronic Arts", "Ubisoft", "Epic Games", "Activision Blizzard"], correctAnswer: "Epic Games", difficulty: "easy" },
            { question: "Jak se jmenuje herní platforma pro streamování, kterou vlastní Amazon?", options: ["YouTube Gaming", "Mixer", "Twitch", "Facebook Gaming"], correctAnswer: "Twitch", difficulty: "easy" },
            { question: "Ve hře Valorant, kolik hráčů je v jednom týmu?", options: ["3", "4", "5", "6"], correctAnswer: "5", difficulty: "easy" },
            { question: "Která hra je známá svými 'kostičkami' a kreativním stavěním?", options: ["Roblox", "Terraria", "Minecraft", "Stardew Valley"], correctAnswer: "Minecraft", difficulty: "easy" },
            { question: "Co je hlavním cílem ve hře 'Among Us' pro člena posádky?", options: ["Sabotovat loď", "Dokončit úkoly", "Lovít impostory", "Schovávat se"], correctAnswer: "Dokončit úkoly", difficulty: "easy" },
            { question: "Jak se jmenuje hlavní hrdina série her 'Super Mario'?", options: ["Luigi", "Wario", "Mario", "Bowser"], correctAnswer: "Mario", difficulty: "easy" },
            { question: "Která konzole je hlavním konkurentem pro PlayStation od Sony?", options: ["Nintendo Switch", "PC", "Xbox", "Stadia"], correctAnswer: "Xbox", difficulty: "easy" },
            { question: "Co znamená zkratka 'NPC' ve hrách?", options: ["New Player Character", "Non-Playable Character", "Nový příběhový cíl", "Nebezpečná postava"], correctAnswer: "Non-Playable Character", difficulty: "easy" },
            { question: "Ve hře 'League of Legends', jak se nazývá hlavní mapa?", options: ["King's Canyon", "Summoner's Rift", "World's Edge", "Inferno"], correctAnswer: "Summoner's Rift", difficulty: "easy" },
            { question: "Která z těchto her je závodní hra?", options: ["FIFA", "Call of Duty", "Need for Speed", "The Sims"], correctAnswer: "Need for Speed", difficulty: "easy" },
            { question: "Jak se jmenuje populární battle royale hra od společnosti EA?", options: ["Fortnite", "PUBG", "Apex Legends", "Warzone"], correctAnswer: "Apex Legends", difficulty: "easy" },
            { question: "Která společnost stojí za herní konzolí Nintendo Switch?", options: ["Sony", "Microsoft", "Sega", "Nintendo"], correctAnswer: "Nintendo", difficulty: "easy" },
        ],
        medium: [
            { question: "Která z následujících her je strategická hra v reálném čase (RTS)?", options: ["StarCraft II", "Overwatch", "Rocket League", "Apex Legends"], correctAnswer: "StarCraft II", difficulty: "medium" },
            { question: "Jak se jmenuje virtuální měna ve hře Minecraft, kterou lze použít k obchodování s vesničany?", options: ["Kredity", "Zlaťáky", "Smaragdy", "Minecoiny"], correctAnswer: "Smaragdy", difficulty: "medium" },
            { question: "Jak se jmenuje engine, na kterém běží hra 'Unreal Tournament' a 'Fortnite'?", options: ["Unity", "CryEngine", "Frostbite", "Unreal Engine"], correctAnswer: "Unreal Engine", difficulty: "medium" },
            { question: "Který z těchto pojmů označuje podvádění ve hrách?", options: ["Grinding", "Cheating", "Farming", "Camping"], correctAnswer: "Cheating", difficulty: "medium" },
            { question: "V jakém roce byla vydána původní hra 'Doom'?", options: ["1989", "1993", "1997", "2001"], correctAnswer: "1993", difficulty: "medium" },
            { question: "Jak se jmenuje hlavní město ve hře 'World of Warcraft' pro frakci Hordy?", options: ["Stormwind", "Ironforge", "Orgrimmar", "Thunder Bluff"], correctAnswer: "Orgrimmar", difficulty: "medium" },
            { question: "Která herní série se odehrává ve fiktivním světě Tamriel?", options: ["The Witcher", "Dragon Age", "Final Fantasy", "The Elder Scrolls"], correctAnswer: "The Elder Scrolls", difficulty: "medium" },
            { question: "Co znamená pojem 'buff' v kontextu her?", options: ["Oslabení postavy", "Dočasné vylepšení", "Chyba ve hře", "Speciální útok"], correctAnswer: "Dočasné vylepšení", difficulty: "medium" },
            { question: "Jak se jmenuje organizace, která pořádá největší turnaj ve hře Dota 2, 'The International'?", options: ["Riot Games", "Blizzard", "Valve", "ESL"], correctAnswer: "Valve", difficulty: "medium" },
            { question: "Která z těchto her je známá svým vysokým stupněm obtížnosti a patří do žánru 'souls-like'?", options: ["Assassin's Creed", "Dark Souls", "Far Cry", "Skyrim"], correctAnswer: "Dark Souls", difficulty: "medium" },
            { question: "Jak se jmenuje hlavní záporák v sérii 'Final Fantasy VII'?", options: ["Kefka", "Ultimecia", "Sephiroth", "Jecht"], correctAnswer: "Sephiroth", difficulty: "medium" },
            { question: "Která hra popularizovala žánr 'battle royale'?", options: ["Fortnite", "H1Z1", "Apex Legends", "PUBG: Battlegrounds"], correctAnswer: "PUBG: Battlegrounds", difficulty: "medium" },
        ],
        hard: [
            { question: "Která hra je považována za průkopníka žánru MOBA?", options: ["Dota 2", "League of Legends", "Smite", "Defense of the Ancients (DotA)"], correctAnswer: "Defense of the Ancients (DotA)", difficulty: "hard" },
            { question: "Jak se jmenuje nejprestižnější turnaj ve hře Counter-Strike?", options: ["The International", "World Championship", "Major", "Captains Draft"], correctAnswer: "Major", difficulty: "hard" },
            { question: "V jaké hře se poprvé objevil 'Konami Code'?", options: ["Contra", "Gradius", "Metal Gear", "Castlevania"], correctAnswer: "Gradius", difficulty: "hard" },
            { question: "Jak se jmenuje tvůrce herní série 'Metal Gear Solid'?", options: ["Shigeru Miyamoto", "Hideo Kojima", "Yuji Naka", "Shinji Mikami"], correctAnswer: "Hideo Kojima", difficulty: "hard" },
            { question: "Který tým vyhrál první 'The International' v Dota 2 v roce 2011?", options: ["Evil Geniuses", "OG", "Natus Vincere (Na'Vi)", "Invictus Gaming"], correctAnswer: "Natus Vincere (Na'Vi)", difficulty: "hard" },
            { question: "Jak se jmenuje jev, kdy chyba ve hře způsobí, že se postava nebo objekt chová nepředvídatelně?", options: ["Bug", "Glitch", "Exploit", "Lag"], correctAnswer: "Glitch", difficulty: "hard" },
            { question: "Jak se jmenuje fiktivní společnost zodpovědná za T-virus v sérii 'Resident Evil'?", options: ["Shinra", "Abstergo", "Umbrella Corporation", "Aperture Science"], correctAnswer: "Umbrella Corporation", difficulty: "hard" },
            { question: "Která z těchto postav není jedním ze čtyř původních 'Ghostů' z Pac-Mana?", options: ["Blinky", "Pinky", "Inky", "Clyde"], correctAnswer: "Clyde", difficulty: "hard" },
            { question: "Jak se nazývá technika ve hře Super Smash Bros., která umožňuje rychlý pohyb po zemi?", options: ["Wavedashing", "Shuffling", "Moonwalking", "Foxtrotting"], correctAnswer: "Wavedashing", difficulty: "hard" },
            { question: "V jaké hře se vyskytuje slavná věta 'The cake is a lie'?", options: ["Half-Life 2", "BioShock", "Portal", "System Shock"], correctAnswer: "Portal", difficulty: "hard" },
            { question: "Jak se jmenuje první boss, kterého potkáte ve hře 'Cuphead'?", options: ["The Root Pack", "Goopy Le Grande", "Hilda Berg", "Cagney Carnation"], correctAnswer: "The Root Pack", difficulty: "hard" },
            { question: "Která herní konzole jako první představila analogovou páčku na svém ovladači?", options: ["PlayStation", "Sega Saturn", "Nintendo 64", "Atari 5200"], correctAnswer: "Nintendo 64", difficulty: "hard" },
        ]
    },
    openEnded: {
        easy: [
            { question: "Co znamená zkratka 'GG', často používaná na konci zápasu?", correctAnswer: "Good game", difficulty: "easy" },
            { question: "Jaký je hlavní cíl ve hře Rocket League?", correctAnswer: "Dát gól", difficulty: "easy" },
            { question: "Jak se jmenuje instalatér v červené čepici od Nintenda?", correctAnswer: "Mario", difficulty: "easy" },
            { question: "Jak se jmenuje hlavní měna ve hře Fortnite?", correctAnswer: "V-Bucks", difficulty: "easy" },
            { question: "Jak se jmenuje nejoblíbenější mapa v Counter-Strike?", correctAnswer: "Dust II", difficulty: "easy" },
            { question: "Co sbírá ježek Sonic?", correctAnswer: "Prsteny", difficulty: "easy" },
            { question: "Jak se jmenuje mobilní hra, kde střílíte ptáky z praku?", correctAnswer: "Angry Birds", difficulty: "easy" },
            { question: "Jak se jmenuje zařízení, které používáte k ovládání her na PC?", correctAnswer: "Klávesnice a myš", difficulty: "easy" },
            { question: "Co znamená pojem 'AFK'?", correctAnswer: "Away from keyboard", difficulty: "easy" },
            { question: "Jak se jmenuje hlavní postava série Tomb Raider?", correctAnswer: "Lara Croft", difficulty: "easy" },
            { question: "Co se snažíte postavit v Tetrisu?", correctAnswer: "Řady", difficulty: "easy" },
            { question: "Jak se jmenuje simulátor života od EA?", correctAnswer: "The Sims", difficulty: "easy" },
        ],
        medium: [
            { question: "Jak se jmenuje hlavní postava v sérii her The Legend of Zelda?", correctAnswer: "Link", difficulty: "medium" },
            { question: "Jak se jmenuje mimozemská rasa, proti které lidstvo bojuje v sérii Halo?", correctAnswer: "Covenant", difficulty: "medium" },
            { question: "Která společnost vyvinula herní engine Frostbite, používaný v sérii Battlefield?", correctAnswer: "DICE", difficulty: "medium" },
            { question: "Jak se jmenuje fiktivní sport hraný na košťatech v sérii Harry Potter?", correctAnswer: "Famfrpál", difficulty: "medium" },
            { question: "Jak se jmenuje démonický lovec, hlavní hrdina série Devil May Cry?", correctAnswer: "Dante", difficulty: "medium" },
            { question: "Co je to 'Easter Egg' ve hře?", correctAnswer: "Skrytá zpráva nebo funkce", difficulty: "medium" },
            { question: "Jak se jmenuje první Pokémon v Pokédexu?", correctAnswer: "Bulbasaur", difficulty: "medium" },
            { question: "Jak se jmenuje meč, který používá Geralt z Rivie?", correctAnswer: "Ocelový a stříbrný meč", difficulty: "medium" },
            { question: "Jak se jmenuje město, ve kterém se odehrává BioShock?", correctAnswer: "Rapture", difficulty: "medium" },
            { question: "Co znamená zkratka 'RPG'?", correctAnswer: "Role-playing game", difficulty: "medium" },
            { question: "Jak se jmenuje tvůrce Minecraftu?", correctAnswer: "Markus Persson", difficulty: "medium" },
            { question: "Jak se jmenuje nejvyšší rank v Counter-Strike: Global Offensive?", correctAnswer: "The Global Elite", difficulty: "medium" },
        ],
        hard: [
            { question: "Z jaké země pochází profesionální hráč 'Faker', legenda hry League of Legends?", correctAnswer: "Jižní Korea", difficulty: "hard" },
            { question: "Která herní série je známá svou post-apokalyptickou pustinou a postavou Vault Boy?", correctAnswer: "Fallout", difficulty: "hard" },
            { question: "Jak se jmenuje virus, který způsobil zombie apokalypsu v sérii Resident Evil?", correctAnswer: "T-virus", difficulty: "hard" },
            { question: "Jak zní první slovo, které se naučíte v jazyce draků ve hře Skyrim?", correctAnswer: "Fus", difficulty: "hard" },
            { question: "Jak se jmenuje umělá inteligence, která pomáhá Master Chiefovi v sérii Halo?", correctAnswer: "Cortana", difficulty: "hard" },
            { question: "Jaký je název pro herní styl, kdy se hráč snaží dokončit hru co nejrychleji?", correctAnswer: "Speedrun", difficulty: "hard" },
            { question: "Jak se jmenuje nechvalně známá vodní úroveň z první hry Teenage Mutant Ninja Turtles na NES?", correctAnswer: "The Dam", difficulty: "hard" },
            { question: "Jak se jmenuje loď, na které se odehrává první díl série Metal Gear Solid?", correctAnswer: "Shadow Moses", difficulty: "hard" },
            { question: "Která hra drží rekord za nejvíce prodaných kopií všech dob?", correctAnswer: "Minecraft", difficulty: "hard" },
            { question: "Jak se jmenuje filozofický koncept, který zkoumá hra 'SOMA'?", correctAnswer: "Identita vědomí", difficulty: "hard" },
            { question: "Jaký je název pro nejvyšší možný počet bodů v původní arkádové hře Donkey Kong?", correctAnswer: "Kill screen", difficulty: "hard" },
            { question: "Která hra jako první obsahovala 'cover system' jako klíčovou mechaniku?", correctAnswer: "Kill Switch", difficulty: "hard" },
        ]
    },
  },
    [Category.SocialMedia]: {
        multipleChoice: {
            easy: [
                 { question: "Která sociální síť byla původně vytvořena pro sdílení krátkých videí?", options: ["Instagram", "Facebook", "TikTok", "Twitter"], correctAnswer: "TikTok", difficulty: "easy" },
                 { question: "Která společnost je mateřskou společností Instagramu a WhatsAppu?", options: ["Alphabet", "Meta", "Microsoft", "Apple"], correctAnswer: "Meta", difficulty: "easy" },
                 { question: "Jaká sociální síť je primárně zaměřena na profesionální networking?", options: ["Pinterest", "Reddit", "LinkedIn", "Tumblr"], correctAnswer: "LinkedIn", difficulty: "easy" },
                 { question: "Jaký symbol se používá pro označení (tagování) uživatele na většině platforem?", options: ["#", "$", "@", "&"], correctAnswer: "@", difficulty: "easy" },
                 { question: "Která platforma je známá pro své mizející 'Příběhy' (Stories)?", options: ["Facebook", "Instagram", "LinkedIn", "Pinterest"], correctAnswer: "Instagram", difficulty: "easy" },
                 { question: "Co znamená ikona 'palec nahoru' na Facebooku?", options: ["Nelíbí se mi", "Sdílet", "Komentovat", "To se mi líbí"], correctAnswer: "To se mi líbí", difficulty: "easy" },
                 { question: "Která aplikace je primárně pro sdílení fotografií a vizuálního obsahu?", options: ["WhatsApp", "Telegram", "Instagram", "Signal"], correctAnswer: "Instagram", difficulty: "easy" },
                 { question: "Jak se nazývá hlavní stránka na Facebooku, kde vidíte příspěvky od přátel?", options: ["Profil", "Zeď", "Novinky", "Marketplace"], correctAnswer: "Novinky", difficulty: "easy" },
                 { question: "Která platforma pro zasílání zpráv je zelená a vlastní ji Meta?", options: ["Telegram", "Signal", "Viber", "WhatsApp"], correctAnswer: "WhatsApp", difficulty: "easy" },
                 { question: "Jak se nazývá proces sdílení cizího příspěvku na Twitteru/X?", options: ["Repost", "Share", "Retweet", "Pin"], correctAnswer: "Retweet", difficulty: "easy" },
                 { question: "Na které sociální síti najdete 'nástěnky' (boards) a 'piny' (pins)?", options: ["Tumblr", "Pinterest", "Reddit", "Flickr"], correctAnswer: "Pinterest", difficulty: "easy" },
                 { question: "Která sociální síť je známá svým logem ducha?", options: ["TikTok", "Snapchat", "Instagram", "WeChat"], correctAnswer: "Snapchat", difficulty: "easy" },
            ],
            medium: [
                 { question: "Jak se nazývají mizející obrázky a videa na Snapchatu a Instagramu?", options: ["Momenty", "Příběhy (Stories)", "Záblesky", "Fleety"], correctAnswer: "Příběhy (Stories)", difficulty: "medium" },
                 { question: "V jakém roce byl založen Facebook?", options: ["2002", "2004", "2006", "2008"], correctAnswer: "2004", difficulty: "medium" },
                 { question: "Jak se jmenuje algoritmus, který určuje, co vidíte na své 'For You' stránce na TikToku?", options: ["PageRank", "EdgeRank", "The Algorithm", "For You algoritmus"], correctAnswer: "For You algoritmus", difficulty: "medium" },
                 { question: "Která sociální síť byla koupena Elonem Muskem v roce 2022?", options: ["Facebook", "Instagram", "Twitter (X)", "Reddit"], correctAnswer: "Twitter (X)", difficulty: "medium" },
                 { question: "Co je to 'hashtag' a k čemu slouží?", options: ["Označení lokace", "Kategorizace obsahu", "Soukromá zpráva", "Uložení příspěvku"], correctAnswer: "Kategorizace obsahu", difficulty: "medium" },
                 { question: "Jak se jmenuje profesionální verze YouTube pro tvůrce hudby?", options: ["YouTube Music", "YouTube Premium", "YouTube Studio", "YouTube Artist"], correctAnswer: "YouTube Music", difficulty: "medium" },
                 { question: "Která platforma byla jednou z prvních, která popularizovala formát 'blogu'?", options: ["MySpace", "LiveJournal", "Friendster", "Tumblr"], correctAnswer: "LiveJournal", difficulty: "medium" },
                 { question: "Jak se nazývá funkce na LinkedIn, která vám umožňuje doporučit dovednosti kolegy?", options: ["Like", "Endorsement", "Recommendation", "Kudos"], correctAnswer: "Endorsement", difficulty: "medium" },
                 { question: "Jak se jmenuje čínská aplikace, která je ekvivalentem TikToku?", options: ["WeChat", "Douyin", "Weibo", "Baidu"], correctAnswer: "Douyin", difficulty: "medium" },
                 { question: "Která sociální síť byla populární před Facebookem a umožňovala si upravit profil pomocí HTML?", options: ["MySpace", "Hi5", "Bebo", "Orkut"], correctAnswer: "MySpace", difficulty: "medium" },
                 { question: "Jak se nazývají živé audio místnosti na Twitteru/X?", options: ["Rooms", "Stages", "Spaces", "Hangouts"], correctAnswer: "Spaces", difficulty: "medium" },
                 { question: "Která sociální síť byla spuštěna společností Google jako konkurence Facebooku a byla neúspěšná?", options: ["Google Buzz", "Google Wave", "Orkut", "Google+"], correctAnswer: "Google+", difficulty: "medium" },
            ],
            hard: [
                { question: "Jak se nazývají komunitní fóra na platformě Reddit?", options: ["Groups", "Boards", "Channels", "Subreddits"], correctAnswer: "Subreddits", difficulty: "hard" },
                { question: "Který ze zakladatelů Twitteru poslal úplně první tweet?", options: ["Evan Williams", "Biz Stone", "Noah Glass", "Jack Dorsey"], correctAnswer: "Jack Dorsey", difficulty: "hard" },
                { question: "Jak se jmenovala krátkovideová aplikace od Twitteru, která byla ukončena v roce 2017?", options: ["Vine", "Reels", "Shorts", "Clips"], correctAnswer: "Vine", difficulty: "hard" },
                { question: "Jaký je název pro algoritmus, který Facebook používá k řazení příspěvků ve vašem feedu?", options: ["PageRank", "SortFeed", "EdgeRank", "NewsFeed AI"], correctAnswer: "EdgeRank", difficulty: "hard" },
                { question: "Která univerzita byla místem, kde byl původně spuštěn Facebook?", options: ["Stanford", "MIT", "Harvard", "Yale"], correctAnswer: "Harvard", difficulty: "hard" },
                { question: "Jak se nazývá decentralizovaná sociální síť, která funguje na principu federace serverů (instancí)?", options: ["Diaspora", "Mastodon", "Minds", "Steemit"], correctAnswer: "Mastodon", difficulty: "hard" },
                { question: "Kdo byl prvním člověkem, který dosáhl 100 milionů sledujících na Instagramu?", options: ["Taylor Swift", "Cristiano Ronaldo", "Selena Gomez", "Kim Kardashian"], correctAnswer: "Selena Gomez", difficulty: "hard" },
                { question: "Jak se jmenuje společnost, která stojí za aplikací Snapchat?", options: ["Snap Inc.", "Meta", "Bytedance", "Match Group"], correctAnswer: "Snap Inc.", difficulty: "hard" },
                { question: "Jak se nazývá sociální síť založená na pozvánkách, která se zaměřuje na audio chat?", options: ["Discord", "Clubhouse", "Telegram", "Slack"], correctAnswer: "Clubhouse", difficulty: "hard" },
                { question: "Jaký je název pro ověřovací protokol, který používá mnoho sociálních sítí pro přihlášení třetích stran?", options: ["OpenID", "SAML", "OAuth", "LDAP"], correctAnswer: "OAuth", difficulty: "hard" },
                { question: "Jak se jmenoval předchůdce TikToku, který byl koupen společností Bytedance?", options: ["Vigo Video", "Dubsmash", "Musical.ly", "Triller"], correctAnswer: "Musical.ly", difficulty: "hard" },
                { question: "V jakém roce Instagram představil funkci 'Stories'?", options: ["2014", "2015", "2016", "2017"], correctAnswer: "2016", difficulty: "hard" },
            ]
        },
        openEnded: {
            easy: [
                { question: "Kdo je hlavním zakladatelem společnosti Facebook (nyní Meta)?", correctAnswer: "Mark Zuckerberg", difficulty: "easy" },
                { question: "Co znamená zkratka 'DM' v kontextu sociálních sítí?", correctAnswer: "Direct Message", difficulty: "easy" },
                { question: "Jak se jmenuje největší platforma pro streamování videa na světě?", correctAnswer: "YouTube", difficulty: "easy" },
                { question: "Jak se jmenuje symbol '#' používaný ke kategorizaci obsahu?", correctAnswer: "Hashtag", difficulty: "easy" },
                { question: "Jak se jmenuje sociální síť, kde 'tweetujete'?", correctAnswer: "Twitter", difficulty: "easy" },
                { question: "Jak se jmenuje funkce na Instagramu pro krátká vertikální videa?", correctAnswer: "Reels", difficulty: "easy" },
                { question: "Jak se jmenuje hlavní konkurent WhatsAppu, známý svou modrou ikonou?", correctAnswer: "Telegram", difficulty: "easy" },
                { question: "Jak se jmenuje aplikace pro videokonference, která se stala populární během pandemie?", correctAnswer: "Zoom", difficulty: "easy" },
                { question: "Co znamená 'influencer'?", correctAnswer: "Vlivná osoba", difficulty: "easy" },
                { question: "Jak se jmenuje proces, kdy někoho přestanete sledovat?", correctAnswer: "Unfollow", difficulty: "easy" },
                { question: "Jak se jmenuje populární platforma pro diskusní fóra?", correctAnswer: "Reddit", difficulty: "easy" },
                { question: "Co je to 'selfie'?", correctAnswer: "Autoportrét", difficulty: "easy" },
            ],
            medium: [
                { question: "Jaký je maximální počet znaků v jednom tweetu na platformě X?", correctAnswer: "280", difficulty: "medium" },
                { question: "V jakém městě sídlí společnost Meta (Facebook)?", correctAnswer: "Menlo Park", difficulty: "medium" },
                { question: "Jak se jmenuje první video, které bylo nahráno na YouTube?", correctAnswer: "Me at the zoo", difficulty: "medium" },
                { question: "Jak se jmenuje čínská společnost, která vlastní TikTok?", correctAnswer: "Bytedance", difficulty: "medium" },
                { question: "Co je to 'phishing' v kontextu online bezpečnosti?", correctAnswer: "Podvodný útok", difficulty: "medium" },
                { question: "Jak se jmenuje funkce na Facebooku pro prodej a nákup věcí?", correctAnswer: "Marketplace", difficulty: "medium" },
                { question: "Jak se jmenuje sociální síť zaměřená na audio, která zažila boom v roce 2021?", correctAnswer: "Clubhouse", difficulty: "medium" },
                { question: "Jak se jmenuje proces ověření účtu, který na sociálních sítích značí modrá fajfka?", correctAnswer: "Verifikace", difficulty: "medium" },
                { question: "Co znamená pojem 'clickbait'?", correctAnswer: "Návnada na kliknutí", difficulty: "medium" },
                { question: "Jak se jmenuje zakladatel sítě LinkedIn?", correctAnswer: "Reid Hoffman", difficulty: "medium" },
                { question: "Co je to 'geotagging'?", correctAnswer: "Označení polohy", difficulty: "medium" },
                { question: "Jak se jmenuje platforma od Googlu pro ukládání a sdílení fotografií?", correctAnswer: "Google Photos", difficulty: "medium" },
            ],
            hard: [
                { question: "Jak se jmenoval ptáček v původním logu Twitteru?", correctAnswer: "Larry", difficulty: "hard" },
                { question: "Jak se jmenuje algoritmus, který YouTube používá k doporučování videí?", correctAnswer: "Google Brain", difficulty: "hard" },
                { question: "V jakém programovacím jazyce byl původně napsán Facebook?", correctAnswer: "PHP", difficulty: "hard" },
                { question: "Jak se jmenuje sociální síť, kterou v roce 2011 spustil Google jako konkurenci Facebooku?", correctAnswer: "Google+", difficulty: "hard" },
                { question: "Jak se jmenuje první osoba, která dosáhla 1 milionu sledujících na Twitteru?", correctAnswer: "Ashton Kutcher", difficulty: "hard" },
                { question: "Jak se nazývá efekt, kdy se malé komunity na internetu radikalizují?", correctAnswer: "Echo chamber", difficulty: "hard" },
                { question: "Jak se jmenuje zakladatel platformy Telegram?", correctAnswer: "Pavel Durov", difficulty: "hard" },
                { question: "Jaký je název pro sociální síť bez reklam, která je financována z předplatného?", correctAnswer: "Ello", difficulty: "hard" },
                { question: "Jak se jmenuje koncept, kdy uživatelé vlastní svá data na sociálních sítích?", correctAnswer: "Decentralizace", difficulty: "hard" },
                { question: "V jakém roce koupil Facebook Instagram?", correctAnswer: "2012", difficulty: "hard" },
                { question: "Jak se jmenuje první 'youtuber', který dosáhl 100 milionů odběratelů?", correctAnswer: "PewDiePie", difficulty: "hard" },
                { question: "Jaký je název pro sociální síť, která je postavena na blockchainu a odměňuje uživatele kryptoměnami?", correctAnswer: "Steemit", difficulty: "hard" },
            ]
        },
    },
    [Category.Culture]: {
        multipleChoice: {
            easy: [
                { question: "Kdo je autorem slavného obrazu 'Mona Lisa'?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correctAnswer: "Leonardo da Vinci", difficulty: "easy" },
                { question: "Kdo napsal slavnou tragédii 'Romeo a Julie'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austenová", "Homér"], correctAnswer: "William Shakespeare", difficulty: "easy" },
                { question: "Ve kterém městě se nachází slavné muzeum Louvre?", options: ["Londýn", "Řím", "New York", "Paříž"], correctAnswer: "Paříž", difficulty: "easy" },
                { question: "Která kapela je známá hity jako 'Bohemian Rhapsody' a 'We Will Rock You'?", options: ["The Rolling Stones", "Queen", "The Beatles", "Led Zeppelin"], correctAnswer: "Queen", difficulty: "easy" },
                { question: "Jak se jmenuje hlavní postava filmové série 'Harry Potter'?", options: ["Ron Weasley", "Hermiona Grangerová", "Albus Brumbál", "Harry Potter"], correctAnswer: "Harry Potter", difficulty: "easy" },
                { question: "Který z těchto nástrojů je smyčcový?", options: ["Klavír", "Kytara", "Housle", "Flétna"], correctAnswer: "Housle", difficulty: "easy" },
                { question: "Jak se jmenuje slavná šikmá věž v Itálii?", options: ["Eiffelova věž", "Big Ben", "Šikmá věž v Pise", "Koloseum"], correctAnswer: "Šikmá věž v Pise", difficulty: "easy" },
                { question: "Které město je dějištěm filmů o Batmanovi?", options: ["Metropolis", "New York", "Gotham City", "Starling City"], correctAnswer: "Gotham City", difficulty: "easy" },
                { question: "Kdo režíroval film 'Titanic' z roku 1997?", options: ["Steven Spielberg", "George Lucas", "James Cameron", "Christopher Nolan"], correctAnswer: "James Cameron", difficulty: "easy" },
                { question: "Z jaké země pochází těstoviny?", options: ["Francie", "Řecko", "Itálie", "Španělsko"], correctAnswer: "Itálie", difficulty: "easy" },
                { question: "Jak se jmenuje filmová cena udělovaná Akademií filmového umění a věd?", options: ["Zlatý glóbus", "BAFTA", "Oscar", "Zlatá palma"], correctAnswer: "Oscar", difficulty: "easy" },
                { question: "Který z těchto malířů si uřízl ucho?", options: ["Claude Monet", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí"], correctAnswer: "Vincent van Gogh", difficulty: "easy" },
            ],
            medium: [
                 { question: "Která kapela vydala slavné album 'The Dark Side of the Moon'?", options: ["The Beatles", "Led Zeppelin", "Queen", "Pink Floyd"], correctAnswer: "Pink Floyd", difficulty: "medium" },
                 { question: "Jak se jmenuje autorka série knih o Harrym Potterovi?", options: ["J. R. R. Tolkien", "George R. R. Martin", "J. K. Rowlingová", "Suzanne Collinsová"], correctAnswer: "J. K. Rowlingová", difficulty: "medium" },
                 { question: "Které umělecké hnutí je spojeno se Salvadorem Dalím?", options: ["Kubismus", "Impresionismus", "Surrealismus", "Expresionismus"], correctAnswer: "Surrealismus", difficulty: "medium" },
                 { question: "Kdo složil hudbu k filmům 'Star Wars' a 'Jurský park'?", options: ["Hans Zimmer", "Ennio Morricone", "John Williams", "Howard Shore"], correctAnswer: "John Williams", difficulty: "medium" },
                 { question: "Jak se jmenuje první celovečerní animovaný film od Walta Disneyho?", options: ["Pinocchio", "Bambi", "Sněhurka a sedm trpaslíků", "Popelka"], correctAnswer: "Sněhurka a sedm trpaslíků", difficulty: "medium" },
                 { question: "Ve kterém století žil William Shakespeare?", options: ["15. a 16. století", "16. a 17. století", "17. a 18. století", "14. a 15. století"], correctAnswer: "16. a 17. století", difficulty: "medium" },
                 { question: "Jak se jmenuje hlavní město Aztécké říše?", options: ["Cuzco", "Tikal", "Chichén Itzá", "Tenochtitlán"], correctAnswer: "Tenochtitlán", difficulty: "medium" },
                 { question: "Který z těchto filozofů byl učitelem Alexandra Velikého?", options: ["Platón", "Sokrates", "Aristotelés", "Pythagoras"], correctAnswer: "Aristotelés", difficulty: "medium" },
                 { question: "Jak se jmenuje japonská forma poezie skládající se ze tří veršů o 5, 7 a 5 slabikách?", options: ["Tanka", "Sonet", "Haiku", "Limerick"], correctAnswer: "Haiku", difficulty: "medium" },
                 { question: "Který film jako první v historii získal 11 Oscarů?", options: ["Titanic", "Pán prstenů: Návrat krále", "Ben-Hur", "Vše o Evě"], correctAnswer: "Ben-Hur", difficulty: "medium" },
                 { question: "Jak se jmenuje umělecký směr, který se vyznačuje geometrickými tvary a více úhly pohledu?", options: ["Futurismus", "Kubismus", "Dadaismus", "Abstrakce"], correctAnswer: "Kubismus", difficulty: "medium" },
                 { question: "Kdo napsal román 'Vojna a mír'?", options: ["Fjodor Dostojevskij", "Anton Čechov", "Alexandr Puškin", "Lev Nikolajevič Tolstoj"], correctAnswer: "Lev Nikolajevič Tolstoj", difficulty: "medium" },
            ],
            hard: [
                 { question: "Kdo je režisérem filmové trilogie 'Pán prstenů'?", options: ["Steven Spielberg", "George Lucas", "James Cameron", "Peter Jackson"], correctAnswer: "Peter Jackson", difficulty: "hard" },
                 { question: "Který hudební skladatel je autorem slavné 'Ódy na radost'?", options: ["Mozart", "Bach", "Ludwig van Beethoven", "Chopin"], correctAnswer: "Ludwig van Beethoven", difficulty: "hard" },
                 { question: "Který z těchto románů nenapsal Franz Kafka?", options: ["Proces", "Zámek", "Proměna", "Cizinec"], correctAnswer: "Cizinec", difficulty: "hard" },
                 { question: "Jak se jmenuje architektonický styl, který se vyznačuje lomenými oblouky, žebrovou klenbou a opěrným systémem?", options: ["Románský", "Baroko", "Renesance", "Gotika"], correctAnswer: "Gotika", difficulty: "hard" },
                 { question: "Kdo je považován za 'otce' filmové sci-fi díky svému filmu 'Cesta na Měsíc' z roku 1902?", options: ["Bratři Lumièrové", "Charlie Chaplin", "Georges Méliès", "D. W. Griffith"], correctAnswer: "Georges Méliès", difficulty: "hard" },
                 { question: "Jak se jmenuje literární cena, která je považována za nejprestižnější ocenění v anglicky psané literatuře?", options: ["Pulitzerova cena", "Nobelova cena za literaturu", "Bookerova cena", "National Book Award"], correctAnswer: "Bookerova cena", difficulty: "hard" },
                 { question: "Který film Quentina Tarantina je známý svou nelineární narativní strukturou?", options: ["Reservoir Dogs", "Pulp Fiction: Historky z podsvětí", "Kill Bill", "Hanebný pancharti"], correctAnswer: "Pulp Fiction: Historky z podsvětí", difficulty: "hard" },
                 { question: "Jak se jmenuje starověká egyptská kniha obsahující magická zaříkávadla pro pomoc zemřelým na onom světě?", options: ["Kniha mrtvých", "Epos o Gilgamešovi", "Tibetská kniha mrtvých", "Kniha Thothova"], correctAnswer: "Kniha mrtvých", difficulty: "hard" },
                 { question: "Který malíř je autorem slavného díla 'Guernica'?", options: ["Joan Miró", "Salvador Dalí", "Francisco Goya", "Pablo Picasso"], correctAnswer: "Pablo Picasso", difficulty: "hard" },
                 { question: "Jak se jmenuje film z roku 1941 od Orsona Wellese, který je často považován za nejlepší film všech dob?", options: ["Casablanca", "Kmotr", "Občan Kane", "Gone with the Wind"], correctAnswer: "Občan Kane", difficulty: "hard" },
                 { question: "Jaký je název pro tradiční korejské oblečení?", options: ["Kimono", "Sárí", "Hanbok", "Cheongsam"], correctAnswer: "Hanbok", difficulty: "hard" },
                 { question: "Kdo napsal slavnou operu 'Kouzelná flétna'?", options: ["Giuseppe Verdi", "Richard Wagner", "Wolfgang Amadeus Mozart", "Johann Strauss"], correctAnswer: "Wolfgang Amadeus Mozart", difficulty: "hard" },
            ]
        },
        openEnded: {
            easy: [
                 { question: "V jakém městě se nachází slavná opera La Scala?", correctAnswer: "Milán", difficulty: "easy" },
                 { question: "Jak se jmenuje japonské umění skládání papíru?", correctAnswer: "Origami", difficulty: "easy" },
                 { question: "Kdo napsal 'Malého prince'?", correctAnswer: "Antoine de Saint-Exupéry", difficulty: "easy" },
                 { question: "Jak se jmenuje socha nahého muže od Michelangela?", correctAnswer: "David", difficulty: "easy" },
                 { question: "Jak se jmenuje kapela, jejíž členové byli John, Paul, George a Ringo?", correctAnswer: "The Beatles", difficulty: "easy" },
                 { question: "Jak se jmenuje nejznámější český hudební skladatel?", correctAnswer: "Bedřich Smetana", difficulty: "easy" },
                 { question: "Jak se jmenuje nejznámější obraz Vincenta van Gogha s noční oblohou?", correctAnswer: "Hvězdná noc", difficulty: "easy" },
                 { question: "Z jaké země pochází sushi?", correctAnswer: "Japonsko", difficulty: "easy" },
                 { question: "Jak se jmenuje hlavní město Francie?", correctAnswer: "Paříž", difficulty: "easy" },
                 { question: "Jak se jmenuje film o mladém lvíčeti, které se má stát králem?", correctAnswer: "Lví král", difficulty: "easy" },
                 { question: "Kdo je králem Rock and Rollu?", correctAnswer: "Elvis Presley", difficulty: "easy" },
                 { question: "Jak se jmenuje autor detektivek s Herculem Poirotem?", correctAnswer: "Agatha Christie", difficulty: "easy" },
            ],
            medium: [
                { question: "Kdo namaloval strop Sixtinské kaple ve Vatikánu?", correctAnswer: "Michelangelo", difficulty: "medium" },
                { question: "Kdo napsal dystopický román '1984'?", correctAnswer: "George Orwell", difficulty: "medium" },
                { question: "Jak se jmenuje architektonický styl Katedrály Notre-Dame v Paříži?", correctAnswer: "Gotika", difficulty: "medium" },
                { question: "Jak se jmenuje filmová série o archeologovi, který nosí klobouk a bič?", correctAnswer: "Indiana Jones", difficulty: "medium" },
                { question: "Jak se jmenuje řecký bůh moře?", correctAnswer: "Poseidon", difficulty: "medium" },
                { question: "Jak se jmenuje hlavní postava románu 'Don Quijote'?", correctAnswer: "Don Quijote de la Mancha", difficulty: "medium" },
                { question: "Který slavný festival se koná v brazilském Rio de Janeiru?", correctAnswer: "Karneval", difficulty: "medium" },
                { question: "Jak se jmenuje autor románu 'Sto roků samoty'?", correctAnswer: "Gabriel García Márquez", difficulty: "medium" },
                { question: "Jak se jmenuje měna používaná v Japonsku?", correctAnswer: "Jen", difficulty: "medium" },
                { question: "Jak se jmenuje první film, který byl natočen kompletně pomocí CGI?", correctAnswer: "Toy Story", difficulty: "medium" },
                { question: "Z jakého jazyka pochází slovo 'déjà vu'?", correctAnswer: "Francouzština", difficulty: "medium" },
                { question: "Které město je známé jako 'Věčné město'?", correctAnswer: "Řím", difficulty: "medium" },
            ],
            hard: [
                 { question: "Z jaké země pochází hudební žánr flamenco?", correctAnswer: "Španělsko", difficulty: "hard" },
                 { question: "Jak se jmenuje ruský skladatel, autor baletu 'Labutí jezero'?", correctAnswer: "Petr Iljič Čajkovskij", difficulty: "hard" },
                 { question: "Jak se jmenuje nejstarší dochovaný epos na světě?", correctAnswer: "Epos o Gilgamešovi", difficulty: "hard" },
                 { question: "Jak se jmenuje filmový festival, kde se udílí Zlatá palma?", correctAnswer: "Filmový festival v Cannes", difficulty: "hard" },
                 { question: "Jak se jmenuje filozofický směr, který zdůrazňuje existenci jednotlivce jako svobodné a zodpovědné bytosti?", correctAnswer: "Existencialismus", difficulty: "hard" },
                 { question: "Jak se jmenuje autor sochy 'Myslitel'?", correctAnswer: "Auguste Rodin", difficulty: "hard" },
                 { question: "Jak se jmenuje styl japonského divadla, který je známý svými propracovanými maskami a kostýmy?", correctAnswer: "Kabuki", difficulty: "hard" },
                 { question: "Jak se jmenuje největší náboženská stavba na světě, nacházející se v Kambodži?", correctAnswer: "Angkor Vat", difficulty: "hard" },
                 { question: "Jak se jmenuje italský režisér, který natočil film 'Sladký život' (La Dolce Vita)?", correctAnswer: "Federico Fellini", difficulty: "hard" },
                 { question: "Jak se jmenuje nejstarší univerzita v anglicky mluvícím světě?", correctAnswer: "Oxfordská univerzita", difficulty: "hard" },
                 { question: "Jak se jmenuje starověké písmo, které používali Sumerové?", correctAnswer: "Klínové písmo", difficulty: "hard" },
                 { question: "Jaký je název pro tradiční čínskou operu, známou svým zpěvem a akrobacií?", correctAnswer: "Pekingská opera", difficulty: "hard" },
            ]
        },
    },
    [Category.Geography]: {
        multipleChoice: {
            easy: [
                { question: "Jaké je hlavní město Austrálie?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctAnswer: "Canberra", difficulty: "easy" },
                { question: "Který oceán je největší na světě?", options: ["Atlantský", "Indický", "Tichý", "Severní ledový"], correctAnswer: "Tichý", difficulty: "easy" },
                { question: "Ve které zemi se nachází Machu Picchu?", options: ["Brazílie", "Mexiko", "Peru", "Kolumbie"], correctAnswer: "Peru", difficulty: "easy" },
                { question: "Která řeka je nejdelší v České republice?", options: ["Morava", "Odra", "Labe", "Vltava"], correctAnswer: "Vltava", difficulty: "easy" },
                { question: "Na kterém kontinentu leží Egypt?", options: ["Asie", "Evropa", "Afrika", "Jižní Amerika"], correctAnswer: "Afrika", difficulty: "easy" },
                { question: "Jak se jmenuje nejvyšší hora světa?", options: ["K2", "Mount Everest", "Kančendženga", "Lhoce"], correctAnswer: "Mount Everest", difficulty: "easy" },
                { question: "Která země je známá svými pyramidami?", options: ["Mexiko", "Egypt", "Čína", "Indie"], correctAnswer: "Egypt", difficulty: "easy" },
                { question: "Jak se jmenuje největší poušť na světě?", options: ["Sahara", "Gobi", "Kalahari", "Antarktická poušť"], correctAnswer: "Antarktická poušť", difficulty: "easy" },
                { question: "Jaké je hlavní město Japonska?", options: ["Kjóto", "Ósaka", "Tokio", "Hirošima"], correctAnswer: "Tokio", difficulty: "easy" },
                { question: "Která země má tvar boty?", options: ["Španělsko", "Řecko", "Itálie", "Norsko"], correctAnswer: "Itálie", difficulty: "easy" },
                { question: "Kolik kontinentů je na Zemi?", options: ["5", "6", "7", "8"], correctAnswer: "7", difficulty: "easy" },
                { question: "Ve kterém městě se nachází Socha svobody?", options: ["Washington D.C.", "Los Angeles", "New York", "Chicago"], correctAnswer: "New York", difficulty: "easy" },
            ],
            medium: [
                { question: "Která řeka protéká Paříží?", options: ["Dunaj", "Rhôna", "Loira", "Seina"], correctAnswer: "Seina", difficulty: "medium" },
                { question: "Jak se jmenuje největší jezero v Africe?", options: ["Tanganika", "Malawi", "Viktoriino jezero", "Čadské jezero"], correctAnswer: "Viktoriino jezero", difficulty: "medium" },
                { question: "Který stát USA je největší rozlohou?", options: ["Texas", "Kalifornie", "Aljaška", "Montana"], correctAnswer: "Aljaška", difficulty: "medium" },
                { question: "Ve kterém pohoří se nachází hora Mont Blanc, nejvyšší vrchol Alp?", options: ["Pyreneje", "Karpaty", "Alpy", "Apeniny"], correctAnswer: "Alpy", difficulty: "medium" },
                { question: "Jak se jmenuje hlavní město Brazílie?", options: ["Rio de Janeiro", "São Paulo", "Salvador", "Brasília"], correctAnswer: "Brasília", difficulty: "medium" },
                { question: "Který průplav spojuje Atlantský a Tichý oceán?", options: ["Suezský průplav", "Panamský průplav", "Korintský průplav", "Kielský průplav"], correctAnswer: "Panamský průplav", difficulty: "medium" },
                { question: "Které moře odděluje Evropu od Afriky?", options: ["Černé moře", "Rudé moře", "Středozemní moře", "Arabské moře"], correctAnswer: "Středozemní moře", difficulty: "medium" },
                { question: "Jak se jmenuje nejsevernější bod pevninské Evropy?", options: ["Nordkapp", "Mys Roca", "Punta de Tarifa", "Mys Sata"], correctAnswer: "Nordkapp", difficulty: "medium" },
                { question: "Které město je známé svými kanály a gondolami?", options: ["Amsterdam", "Bruggy", "Benátky", "Stockholm"], correctAnswer: "Benátky", difficulty: "medium" },
                { question: "Jak se jmenuje největší korálový útes na světě?", options: ["Korálový trojúhelník", "Belizský bariérový útes", "Velký bariérový útes", "Rudomořský útes"], correctAnswer: "Velký bariérový útes", difficulty: "medium" },
                { question: "Která země je známá jako 'Říše středu'?", options: ["Japonsko", "Korea", "Vietnam", "Čína"], correctAnswer: "Čína", difficulty: "medium" },
                { question: "Které pohoří tvoří přirozenou hranici mezi Evropou a Asií?", options: ["Alpy", "Kavkaz", "Ural", "Himaláj"], correctAnswer: "Ural", difficulty: "medium" },
            ],
            hard: [
                { question: "Která řeka je nejdelší na světě?", options: ["Nil", "Amazonka", "Jang-c'-ťiang", "Mississippi"], correctAnswer: "Amazonka", difficulty: "hard" },
                { question: "Jak se jmenuje nejdelší pohoří na světě?", options: ["Himaláj", "Andy", "Skalnaté hory", "Ural"], correctAnswer: "Andy", difficulty: "hard" },
                { question: "Jak se jmenuje nejníže položené místo na zemském povrchu?", options: ["Údolí smrti", "Mrtvé moře", "Asalská proláklina", "Bajkal"], correctAnswer: "Mrtvé moře", difficulty: "hard" },
                { question: "Které město leží na dvou kontinentech?", options: ["Káhira", "Panama City", "Istanbul", "Suez"], correctAnswer: "Istanbul", difficulty: "hard" },
                { question: "Jak se jmenuje největší vnitrozemský stát na světě?", options: ["Mongolsko", "Kazachstán", "Čad", "Bolívie"], correctAnswer: "Kazachstán", difficulty: "hard" },
                { question: "Která země má nejdelší pobřeží?", options: ["Austrálie", "Indonésie", "Rusko", "Kanada"], correctAnswer: "Kanada", difficulty: "hard" },
                { question: "Jak se jmenuje jev, kdy se teplá oceánská voda v Tichém oceánu přesouvá na východ a ovlivňuje počasí po celém světě?", options: ["La Niña", "El Niño", "Monzun", "Golfský proud"], correctAnswer: "El Niño", difficulty: "hard" },
                { question: "Jak se jmenuje souostroví, které Charles Darwin studoval při formulování své teorie evoluce?", options: ["Havajské ostrovy", "Galapágy", "Kanárské ostrovy", "Filipíny"], correctAnswer: "Galapágy", difficulty: "hard" },
                { question: "Které hlavní město je nejvýše položené na světě?", options: ["Quito", "Bogota", "La Paz", "Thimphu"], correctAnswer: "La Paz", difficulty: "hard" },
                { question: "Jak se jmenuje největší aktivní sopka na světě?", options: ["Etna", "Mauna Loa", "Fudži", "Krakatoa"], correctAnswer: "Mauna Loa", difficulty: "hard" },
                { question: "Jak se nazývá vědecké studium jeskyní?", options: ["Speleologie", "Potamologie", "Glaciologie", "Limnologie"], correctAnswer: "Speleologie", difficulty: "hard" },
                { question: "Který stát je zároveň kontinentem?", options: ["Grónsko", "Antarktida", "Austrálie", "Indie"], correctAnswer: "Austrálie", difficulty: "hard" },
            ]
        },
        openEnded: {
            easy: [
                 { question: "Která země je známá jako 'Země vycházejícího slunce'?", correctAnswer: "Japonsko", difficulty: "easy" },
                 { question: "Na kterém kontinentu se nachází poušť Sahara?", correctAnswer: "Afrika", difficulty: "easy" },
                 { question: "Jaké je hlavní město Kanady?", correctAnswer: "Ottawa", difficulty: "easy" },
                 { question: "Která řeka protéká Londýnem?", correctAnswer: "Temže", difficulty: "easy" },
                 { question: "Jak se jmenuje největší deštný prales na světě?", correctAnswer: "Amazonský prales", difficulty: "easy" },
                 { question: "Ve kterém státě USA se nachází Grand Canyon?", correctAnswer: "Arizona", difficulty: "easy" },
                 { question: "Jak se jmenuje nejvyšší hora Afriky?", correctAnswer: "Kilimandžáro", difficulty: "easy" },
                 { question: "Která země je nejlidnatější na světě?", correctAnswer: "Indie", difficulty: "easy" },
                 { question: "Ve kterém městě se nachází Kreml?", correctAnswer: "Moskva", difficulty: "easy" },
                 { question: "Jak se jmenuje nejdelší řeka v Evropě?", correctAnswer: "Volha", difficulty: "easy" },
                 { question: "Které dva státy tvoří Pyrenejský poloostrov?", correctAnswer: "Španělsko a Portugalsko", difficulty: "easy" },
                 { question: "Jak se jmenuje hlavní město Německa?", correctAnswer: "Berlín", difficulty: "easy" },
            ],
            medium: [
                { question: "Jak se jmenuje největší ostrov světa?", correctAnswer: "Grónsko", difficulty: "medium" },
                { question: "Který průliv odděluje Velkou Británii od Francie?", correctAnswer: "Lamanšský průliv", difficulty: "medium" },
                { question: "Jak se jmenuje nejjižnější cíp Jižní Ameriky?", correctAnswer: "Mys Horn", difficulty: "medium" },
                { question: "Které jezero je nejhlubší na světě?", correctAnswer: "Bajkal", difficulty: "medium" },
                { question: "Jak se jmenuje největší poloostrov světa?", correctAnswer: "Arabský poloostrov", difficulty: "medium" },
                { question: "Jak se jmenuje hlavní město Nového Zélandu?", correctAnswer: "Wellington", difficulty: "medium" },
                { question: "Které pohoří se táhne podél západního pobřeží Jižní Ameriky?", correctAnswer: "Andy", difficulty: "medium" },
                { question: "Jak se jmenuje největší stát v Jižní Americe?", correctAnswer: "Brazílie", difficulty: "medium" },
                { question: "Která země je známá jako 'Země tisíců jezer'?", correctAnswer: "Finsko", difficulty: "medium" },
                { question: "Jak se jmenuje město zničené výbuchem sopky Vesuv v roce 79 n.l.?", correctAnswer: "Pompeje", difficulty: "medium" },
                { question: "Jak se jmenuje největší africká země podle rozlohy?", correctAnswer: "Alžírsko", difficulty: "medium" },
                { question: "Které dva oceány spojuje Beringův průliv?", correctAnswer: "Tichý a Severní ledový", difficulty: "medium" },
            ],
            hard: [
                 { question: "Jak se nazývá největší poušť světa?", correctAnswer: "Antarktická poušť", difficulty: "hard" },
                 { question: "Který průliv odděluje Evropu od Afriky?", correctAnswer: "Gibraltarský průliv", difficulty: "hard" },
                 { question: "Jak se jmenuje nejdeštivější místo na Zemi?", correctAnswer: "Mawsynram", difficulty: "hard" },
                 { question: "Jak se jmenuje největší delta řeky na světě, tvořená Gangu a Brahmaputrou?", correctAnswer: "Bengálská delta", difficulty: "hard" },
                 { question: "Jak se jmenuje bod na Zemi, který je nejvzdálenější od jakékoliv pevniny?", correctAnswer: "Bod Nemo", difficulty: "hard" },
                 { question: "Jak se jmenuje hlavní město Bhútánu?", correctAnswer: "Thimphu", difficulty: "hard" },
                 { question: "Jak se jmenuje stát, který má nejvíce časových pásem?", correctAnswer: "Francie", difficulty: "hard" },
                 { question: "Jak se jmenuje největší ostrov v Středozemním moři?", correctAnswer: "Sicílie", difficulty: "hard" },
                 { question: "Jak se jmenuje největší ledovec na světě?", correctAnswer: "Lambertův ledovec", difficulty: "hard" },
                 { question: "Která země má nejvíce sopek?", correctAnswer: "Indonésie", difficulty: "hard" },
                 { question: "Jak se jmenuje nejstarší hlavní město na světě?", correctAnswer: "Damašek", difficulty: "hard" },
                 { question: "Jak se jmenuje jediná země, jejíž jméno v angličtině začíná na 'Q'?", correctAnswer: "Katar", difficulty: "hard" },
            ]
        },
    },
    [Category.Science]: {
        multipleChoice: {
            easy: [
                { question: "Jaká je chemická značka pro zlato?", options: ["Ag", "Au", "Fe", "Pb"], correctAnswer: "Au", difficulty: "easy" },
                { question: "Která planeta je v naší sluneční soustavě nejblíže Slunci?", options: ["Venuše", "Mars", "Merkur", "Země"], correctAnswer: "Merkur", difficulty: "easy" },
                { question: "Jaký plyn je nejhojněji zastoupen v zemské atmosféře?", options: ["Kyslík", "Oxid uhličitý", "Argon", "Dusík"], correctAnswer: "Dusík", difficulty: "easy" },
                { question: "Co je H₂O?", options: ["Kyselina sírová", "Oxid uhličitý", "Voda", "Peroxid vodíku"], correctAnswer: "Voda", difficulty: "easy" },
                { question: "Která síla nás drží na zemi?", options: ["Magnetismus", "Tření", "Odstředivá síla", "Gravitace"], correctAnswer: "Gravitace", difficulty: "easy" },
                { question: "Kolik planet má naše sluneční soustava?", options: ["7", "8", "9", "10"], correctAnswer: "8", difficulty: "easy" },
                { question: "Jak se nazývá proces, při kterém se voda mění v led?", options: ["Tání", "Vypařování", "Tuhnutí", "Sublimace"], correctAnswer: "Tuhnutí", difficulty: "easy" },
                { question: "Která část rostliny absorbuje vodu a živiny z půdy?", options: ["Listy", "Květy", "Stonek", "Kořeny"], correctAnswer: "Kořeny", difficulty: "easy" },
                { question: "Jak se jmenuje největší orgán lidského těla?", options: ["Játra", "Mozek", "Plíce", "Kůže"], correctAnswer: "Kůže", difficulty: "easy" },
                { question: "Který plyn dýcháme, abychom přežili?", options: ["Dusík", "Kyslík", "Oxid uhličitý", "Vodík"], correctAnswer: "Kyslík", difficulty: "easy" },
                { question: "Která planeta je známá jako 'Rudá planeta'?", options: ["Venuše", "Jupiter", "Mars", "Saturn"], correctAnswer: "Mars", difficulty: "easy" },
                { question: "Jak se nazývá studium živých organismů?", options: ["Chemie", "Fyzika", "Geologie", "Biologie"], correctAnswer: "Biologie", difficulty: "easy" },
            ],
            medium: [
                { question: "Kolik kostí má dospělý člověk?", options: ["206", "212", "198", "220"], correctAnswer: "206", difficulty: "medium" },
                { question: "Jak se nazývá 'elektrárna' buňky?", options: ["Jádro", "Ribozom", "Mitochondrie", "Vakuola"], correctAnswer: "Mitochondrie", difficulty: "medium" },
                { question: "Jaký prvek je nejlehčí v periodické tabulce?", options: ["Helium", "Lithium", "Vodík", "Berylium"], correctAnswer: "Vodík", difficulty: "medium" },
                { question: "Co měří Richterova stupnice?", options: ["Sílu větru", "Intenzitu zvuku", "Sílu zemětřesení", "Kyselost roztoku"], correctAnswer: "Sílu zemětřesení", difficulty: "medium" },
                { question: "Jak se nazývá proces, při kterém rostliny vyrábějí potravu pomocí slunečního světla?", options: ["Dýchání", "Transpirace", "Fotosyntéza", "Osmóza"], correctAnswer: "Fotosyntéza", difficulty: "medium" },
                { question: "Který z těchto kovů je za pokojové teploty kapalný?", options: ["Olovo", "Železo", "Rtuť", "Hliník"], correctAnswer: "Rtuť", difficulty: "medium" },
                { question: "Jak se jmenuje největší planeta v naší sluneční soustavě?", options: ["Saturn", "Jupiter", "Neptun", "Uran"], correctAnswer: "Jupiter", difficulty: "medium" },
                { question: "Jak se nazývá věda o počasí?", options: ["Ekologie", "Meteorologie", "Astronomie", "Seismologie"], correctAnswer: "Meteorologie", difficulty: "medium" },
                { question: "Která krevní skupina je univerzální dárce?", options: ["A", "B", "AB", "0"], correctAnswer: "0", difficulty: "medium" },
                { question: "Jaký je chemický symbol pro stříbro?", options: ["Si", "Au", "Ag", "Fe"], correctAnswer: "Ag", difficulty: "medium" },
                { question: "Jak se nazývá jednotka elektrického proudu?", options: ["Volt", "Watt", "Ohm", "Ampér"], correctAnswer: "Ampér", difficulty: "medium" },
                { question: "Která část ucha je zodpovědná za rovnováhu?", options: ["Bubínek", "Hlemýžď", "Vestibulární aparát", "Kladívko"], correctAnswer: "Vestibulární aparát", difficulty: "medium" },
            ],
            hard: [
                { question: "Kdo je autorem teorie relativity?", options: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Nikola Tesla"], correctAnswer: "Albert Einstein", difficulty: "hard" },
                { question: "Jaká je přibližná rychlost světla ve vakuu (v km/s)?", options: ["300 000", "150 000", "500 000", "1 000 000"], correctAnswer: "300 000", difficulty: "hard" },
                { question: "Jak se nazývá jev, kdy světlo mění směr při průchodu z jednoho prostředí do druhého?", options: ["Odraz", "Rozptyl", "Difrakce", "Lom"], correctAnswer: "Lom", difficulty: "hard" },
                { question: "Která částice je zodpovědná za přenos elektrického náboje?", options: ["Proton", "Neutron", "Elektron", "Foton"], correctAnswer: "Elektron", difficulty: "hard" },
                { question: "Jak se nazývá nejtvrdší přírodní minerál?", options: ["Křemen", "Topaz", "Korund", "Diamant"], correctAnswer: "Diamant", difficulty: "hard" },
                { question: "Co je to 'černá díra'?", options: ["Hvězda bez světla", "Studená planeta", "Objekt s extrémní gravitací", "Mlhovina"], correctAnswer: "Objekt s extrémní gravitací", difficulty: "hard" },
                { question: "Jak se nazývá proces, při kterém se jádro atomu štěpí a uvolňuje energii?", options: ["Fúze", "Rozpad beta", "Štěpení", "Ionizace"], correctAnswer: "Štěpení", difficulty: "hard" },
                { question: "Která z těchto kyselin se nachází v lidském žaludku?", options: ["Kyselina sírová", "Kyselina dusičná", "Kyselina chlorovodíková", "Kyselina octová"], correctAnswer: "Kyselina chlorovodíková", difficulty: "hard" },
                { question: "Jak se jmenuje Nobelova cena, která není udílena za vědecký objev?", options: ["Cena za fyziku", "Cena za chemii", "Cena za mír", "Cena za medicínu"], correctAnswer: "Cena za mír", difficulty: "hard" },
                { question: "Jak se nazývá nejmenší jednotka života?", options: ["Atom", "Molekula", "Buňka", "Orgán"], correctAnswer: "Buňka", difficulty: "hard" },
                { question: "Jak se jmenuje číslo 6.022 x 10²³?", options: ["Planckova konstanta", "Gravitační konstanta", "Avogadrova konstanta", "Rychlost světla"], correctAnswer: "Avogadrova konstanta", difficulty: "hard" },
                { question: "Který prvek je základem veškerého organického života?", options: ["Kyslík", "Vodík", "Uhlík", "Dusík"], correctAnswer: "Uhlík", difficulty: "hard" },
            ]
        },
        openEnded: {
            easy: [
                 { question: "Jak se běžně nazývá chemická sloučenina H₂O?", correctAnswer: "Voda", difficulty: "easy" },
                 { question: "Která planeta je známá svými prstenci?", correctAnswer: "Saturn", difficulty: "easy" },
                 { question: "Který prvek má v periodické tabulce protonové číslo 1?", correctAnswer: "Vodík", difficulty: "easy" },
                 { question: "Jak se nazývá hlavní zdroj energie pro Zemi?", correctAnswer: "Slunce", difficulty: "easy" },
                 { question: "Jak se nazývá síla, která zpomaluje pohyb?", correctAnswer: "Tření", difficulty: "easy" },
                 { question: "Kolik nohou má pavouk?", correctAnswer: "8", difficulty: "easy" },
                 { question: "Jak se nazývá proces, kdy se housenka mění v motýla?", correctAnswer: "Metamorfóza", difficulty: "easy" },
                 { question: "Jaká je barva krve?", correctAnswer: "Červená", difficulty: "easy" },
                 { question: "Jak se jmenuje největší zvíře na světě?", correctAnswer: "Plejtvák obrovský", difficulty: "easy" },
                 { question: "Jak se nazývá studium hvězd a vesmíru?", correctAnswer: "Astronomie", difficulty: "easy" },
                 { question: "Co způsobuje střídání dne a noci?", correctAnswer: "Rotace Země", difficulty: "easy" },
                 { question: "Jaký je chemický symbol pro kyslík?", correctAnswer: "O", difficulty: "easy" },
            ],
            medium: [
                { question: "Co znamená zkratka DNA?", correctAnswer: "Deoxyribonukleová kyselina", difficulty: "medium" },
                { question: "Kdo objevil penicilin?", correctAnswer: "Alexander Fleming", difficulty: "medium" },
                { question: "Jak se nazývá proces, kdy pevná látka přechází přímo do plynného stavu?", correctAnswer: "Sublimace", difficulty: "medium" },
                { question: "Jak se nazývá zvuk rychlejší než rychlost zvuku?", correctAnswer: "Nadzvukový", difficulty: "medium" },
                { question: "Která část mozku je zodpovědná za myšlení a paměť?", correctAnswer: "Mozková kůra", difficulty: "medium" },
                { question: "Jak se nazývá stupnice pro měření kyselosti a zásaditosti?", correctAnswer: "pH", difficulty: "medium" },
                { question: "Jak se jmenuje nejbližší galaxie k naší Mléčné dráze?", correctAnswer: "Galaxie v Andromedě", difficulty: "medium" },
                { question: "Kdo formuloval tři zákony pohybu?", correctAnswer: "Isaac Newton", difficulty: "medium" },
                { question: "Jak se nazývá studium hub?", correctAnswer: "Mykologie", difficulty: "medium" },
                { question: "Jak se nazývá ochranná vrstva kolem Země, která nás chrání před UV zářením?", correctAnswer: "Ozonová vrstva", difficulty: "medium" },
                { question: "Jaký je název pro atomy stejného prvku s různým počtem neutronů?", correctAnswer: "Izotopy", difficulty: "medium" },
                { question: "Kdo je považován za otce genetiky?", correctAnswer: "Gregor Mendel", difficulty: "medium" },
            ],
            hard: [
                { question: "Jak se nazývá proces, při kterém rostliny přeměňují světelnou energii na chemickou?", correctAnswer: "Fotosyntéza", difficulty: "hard" },
                { question: "Jak se nazývá síla, která přitahuje objekty k sobě?", correctAnswer: "Gravitace", difficulty: "hard" },
                { question: "Jak se nazývá hypotetická částice, která se pohybuje rychleji než světlo?", correctAnswer: "Tachyon", difficulty: "hard" },
                { question: "Jak se jmenuje teorie, která popisuje vznik vesmíru?", correctAnswer: "Velký třesk", difficulty: "hard" },
                { question: "Jak se nazývá jev, kdy se dvě lehká atomová jádra spojí a vytvoří těžší jádro?", correctAnswer: "Jaderná fúze", difficulty: "hard" },
                { question: "Jak se jmenuje největší měsíc ve sluneční soustavě?", correctAnswer: "Ganymed", difficulty: "hard" },
                { question: "Jak se jmenuje konstanta, která definuje nejmenší možné množství energie?", correctAnswer: "Planckova konstanta", difficulty: "hard" },
                { question: "Jak se nazývá studium hmyzu?", correctAnswer: "Entomologie", difficulty: "hard" },
                { question: "Jak se jmenuje princip, který říká, že nelze současně přesně určit polohu a hybnost částice?", correctAnswer: "Heisenbergův princip neurčitosti", difficulty: "hard" },
                { question: "Jaký je název pro sedmou planetu od Slunce?", correctAnswer: "Uran", difficulty: "hard" },
                { question: "Jak se jmenuje proces, při kterém se genetická informace z DNA přepisuje do RNA?", correctAnswer: "Transkripce", difficulty: "hard" },
                { question: "Jak se nazývá nejvzdálenější vrstva sluneční atmosféry, viditelná při zatmění?", correctAnswer: "Koróna", difficulty: "hard" },
            ]
        },
    },
};
